#- alias: Turn on downstairs lights when motion is detected
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.mijia_motion_stairs_occupancy
#        - binary_sensor.mijia_motion_basement_stairs_occupancy
#        - binary_sensor.mijia_motion_entrance_occupancy
#        - binary_sensor.mijia_motion_kitchen_occupancy
#        - binary_sensor.mijia_motion_livingroom_occupancy
#        - binary_sensor.mijia_motion_livingroom_tv_occupancy
#        - binary_sensor.sr501_pir_motion_stairs
#        - binary_sensor.sr501_pir_motion_livingroom
#      to: 'on'
#  action:
#   - service: light.turn_on
#      entity_id:
#        - light.kitchen
#        - light.table
#        - light.livingroom
#
#- alias: Turn off downstairs lights after 30 minutes of inactivity
#  trigger:
#    - platform: state
#      entity_id:
#        - group.motion_downstairs
#      to: 'off'
#      for:
#        minutes: 30
#  action:
#    - service: light.turn_off
#      entity_id:
#        - light.kitchen
#        - light.table
#        - light.livingroom

#- alias: Turn on office light when motion is detected
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.sr501_pir_motion_playroom
#        - binary_sensor.mijia_motion_basement_stairs_occupancy
#        - binary_sensor.sensor_basement_sr501_pir_motion
#        - binary_sensor.mijia_motion_office_jasmin_occupancy
#      to: 'on'
#  action:
#    - service: light.turn_on
#      entity_id:
#        - light.office_light
#
#- alias: Turn off office light 30 minutes after last movement
#  trigger:
#    - platform: state
#      entity_id:
#        - group.motion_office
#      to: 'off'
#      for:
#        minutes: 30
#  action:
#    - service: light.turn_off
#      entity_id:
#        - light.office_light

- alias: Update Configuration on Gitlab Push Event
  id: update_config_gitlab_push_event

  trigger:
    - platform: webhook
      webhook_id: !secret webhook_id
      allowed_methods:
        - POST
        - PUT
      local_only: true

  action:
    - service: shell_command.update_config
    - service: homeassistant.restart


- alias: Count Motion Active Minutes Aqara Office
  id: count_motion_active_minutes_aqara_office
  description: Increments the motion active minutes counter every minute
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: binary_sensor.aqara_motion_office_occupancy
      state: "on"
  action:
    - service: input_number.increment
      target:
        entity_id: input_number.count_motion_time
  mode: single

- alias: Reset Motion Active Minutes
  description: Resets the motion active minutes counter at midnight
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.count_motion_time
      data:
        value: 0
  mode: single
