---
- platform: history_stats
  name: Computer Alexroom Weekly Runtime
  unique_id: computer_alexroom_weekly_runtime
  entity_id: binary_sensor.computer_alexroom_status
  state: "on"
  type: time
  duration:
    days: 7
