title: ESPHome
badges: []
cards:

  # ESPHome Sensor Kitchen
  - title: Sensor Kitchen
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.sensor_kitchen_firmware
      - entity: sensor.sensor_kitchen_wifi_ip
      - entity: sensor.sensor_kitchen_wifi_strength
      # - entity: sensor.sensor_kitchen_uptime
      - entity: sensor.sensor_kitchen_htu21d_temperature
      - entity: sensor.sensor_kitchen_htu21d_humidity
      - entity: binary_sensor.sensor_kitchen_sr501_pir_motion
      - entity: light.sensor_kitchen_nightlight

  # ESPHome Sensor Stairs
  - title: Sensor Stairs
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.sensor_stairs_firmware
      - entity: sensor.sensor_stairs_wifi_ip
      - entity: sensor.sensor_stairs_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: sensor.sensor_stairs_htu21d_temperature
      - entity: sensor.sensor_stairs_htu21d_humidity
      - entity: sensor.sensor_stairs_tsl2561_ambient_light
      - entity: binary_sensor.sensor_stairs_sr501_pir_motion

  # ESPHome Switch Livingroom
  - title: Switch Livingroom
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.switch_livingroom_firmware
      - entity: sensor.switch_livingroom_wifi_ip
      - entity: sensor.switch_livingroom_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: switch.switch_livingroom_relay
      - entity: binary_sensor.switch_livingroom_touchpad

  # ESPHome Sensor Office
  - title: Sensor Office
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.sensor_office_firmware
      - entity: sensor.sensor_office_wifi_ip
      - entity: sensor.sensor_office_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: sensor.sensor_office_htu21d_temperature
      - entity: sensor.sensor_office_htu21d_humidity
      - entity: sensor.sensor_office_tsl2561_ambient_light
      - entity: binary_sensor.sensor_office_sr501_pir_motion

  # ESPHome Switch IRPanel 1
  - title: Switch IRPanel 1
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.switch_irpanel_1_firmware
      - entity: sensor.switch_irpanel_1_wifi_ip
      - entity: sensor.switch_irpanel_1_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: switch.switch_irpanel_1_relay
      - entity: sensor.switch_irpanel_1_current
      - entity: sensor.switch_irpanel_1_voltage
      - entity: sensor.switch_irpanel_1_power
      - entity: sensor.switch_irpanel_1_total_daily_energy

  # ESPHome Switch IRPanel 2
  - title: Switch IRPanel 2
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.switch_irpanel_2_firmware
      - entity: sensor.switch_irpanel_2_wifi_ip
      - entity: sensor.switch_irpanel_2_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: switch.switch_irpanel_2_relay
      - entity: sensor.switch_irpanel_2_current
      - entity: sensor.switch_irpanel_2_voltage
      - entity: sensor.switch_irpanel_2_power
      - entity: sensor.switch_irpanel_2_total_daily_energy

  # ESPHome Switch Office
  - title: Switch Office
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.switch_office_firmware
      - entity: sensor.switch_office_wifi_ip
      - entity: sensor.switch_office_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: switch.switch_office_relay
      - entity: binary_sensor.switch_office_touchpad

  # ESPHome Sensor Basement
  - title: Sensor Basement
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.sensor_basement_firmware
      - entity: sensor.sensor_basement_wifi_ip
      - entity: sensor.sensor_basement_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: sensor.sensor_basement_htu21d_temperature
      - entity: sensor.sensor_basement_htu21d_humidity
      - entity: sensor.sensor_basement_tsl2561_ambient_light
      - entity: binary_sensor.sensor_basement_sr501_pir_motion

  # ESPHome Switch Basement
  - title: Switch Basement
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.switch_basement_firmware
      - entity: sensor.switch_basement_wifi_ip
      - entity: sensor.switch_basement_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: switch.switch_basement_relay
      - entity: sensor.switch_basement_current
      - entity: sensor.switch_basement_voltage
      - entity: sensor.switch_basement_power
      - entity: sensor.switch_basement_total_daily_energy

  # ESPHome Sensor Heating
  - title: Sensor Heating
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.sensor_heating_firmware
      - entity: sensor.sensor_heating_wifi_ip
      - entity: sensor.sensor_heating_wifi_strength
      # - entity: sensor.sensor_office_uptime
      - entity: sensor.sensor_heating_temperature_flow_groundfloor
      - entity: sensor.sensor_heating_temperature_return_groundfloor
      - entity: sensor.sensor_heating_temperature_flow_upstairs
      - entity: sensor.sensor_heating_temperature_return_upstairs

  - entities:
      - entity: sensor.device_firmware_entrance
      - entity: sensor.wifi_ip_entrance
      - entity: sensor.wifi_ssid_entrance
      - entity: sensor.wifi_signal_entrance
      - entity: sensor.device_uptime_entrance
      - entity: sensor.htu21d_temperature_entrance
      - entity: sensor.htu21d_humidity_entrance
      - entity: binary_sensor.sr501_pir_motion_entrance
      - entity: sensor.tsl2561_ambient_light_entrance
      - entity: light.ws2812b_led_entrance
    show_header_toggle: false
    title: Entrance
    type: entities

  - entities:
      - entity: sensor.device_firmware_livingroom
      - entity: sensor.wifi_ip_livingroom
      - entity: sensor.wifi_ssid_livingroom
      - entity: sensor.wifi_signal_livingroom
      - entity: sensor.device_uptime_livingroom
      - entity: sensor.htu21d_temperature_livingroom
      - entity: sensor.htu21d_humidity_livingroom
      - entity: binary_sensor.sr501_pir_motion_livingroom
      - entity: sensor.tsl2561_ambient_light_livingroom
      - entity: light.ws2812b_led_livingroom
    show_header_toggle: false
    title: Livingroom
    type: entities


  - entities:
      - entity: sensor.device_firmware_bathroom
      - entity: sensor.wifi_ip_bathroom
      - entity: sensor.wifi_ssid_bathroom
      - entity: sensor.wifi_signal_bathroom
      - entity: sensor.device_uptime_bathroom
      - entity: sensor.htu21d_temperature_bathroom
      - entity: sensor.htu21d_humidity_bathroom
      - entity: sensor.bmp180_pressure_bathroom
      - entity: sensor.bmp180_temperature_bathroom
      - entity: binary_sensor.sr501_pir_motion_bathroom
      - entity: sensor.tsl2561_ambient_light_bathroom
      - entity: light.ws2812b_led_bathroom
    show_header_toggle: false
    title: Bathroom
    type: entities

  - entities:
      - entity: sensor.device_firmware_alex_room
      - entity: sensor.wifi_ip_alex_room
      - entity: sensor.wifi_ssid_alex_room
      - entity: sensor.wifi_signal_alex_room
      - entity: sensor.device_uptime_alex_room
      - entity: sensor.htu21d_temperature_alex_room
      - entity: sensor.htu21d_humidity_alex_room
      - entity: sensor.tsl2561_ambient_light_alex_room
      - entity: binary_sensor.sr501_pir_motion_alex_room
    show_header_toggle: false
    title: Alex Room
    type: entities
  - entities:
      - entity: sensor.device_firmware_bedroom
      - entity: sensor.wifi_ip_bedroom
      - entity: sensor.wifi_ssid_bedroom
      - entity: sensor.wifi_signal_bedroom
      - entity: sensor.device_uptime_bedroom
      - entity: sensor.htu21d_temperature_bedroom
      - entity: sensor.htu21d_humidity_bedroom
      - entity: binary_sensor.sr501_pir_motion_bedroom
      - entity: light.ws2812b_led_bedroom
    show_header_toggle: false
    title: Bedroom
    type: entities
  - entities:
      - entity: sensor.device_firmware_domi_room
      - entity: sensor.wifi_ip_domi_room
      - entity: sensor.wifi_ssid_domi_room
      - entity: sensor.wifi_signal_domi_room
      - entity: sensor.device_uptime_domi_room
      - entity: sensor.htu21d_temperature_domi_room
      - entity: sensor.htu21d_humidity_domi_room
#      - entity: sensor.tsl2561_ambient_light_domi_room
#      - entity: binary_sensor.sr501_pir_motion_domi_room
      - entity: light.ws2812b_led_domi_room
    show_header_toggle: false
    title: Domi Room
    type: entities
