---
sensor:
  - default_entity_id: sensor.climate_livingroom_runtime
    unique_id: climate_livingroom_runtime
    name: Climate Livingroom Runtime
    device_class: duration
    unit_of_measurement: min
    icon: >
      {% if is_state('climate.livingroom', 'cool') %}
        mdi:timer-play-outline
      {% else %}
        mdi:timer-off-outline
      {% endif %}
    state: >
      {% if is_state('climate.livingroom', 'cool') %}
        {{ (now().timestamp() - as_timestamp(states.input_datetime.climate_livingroom_start_time.state)) / 60 }}
      {% else %}
        0
      {% endif %}
