---
sensor:
  - default_entity_id: sensor.dominik_combined_screentime
    unique_id: dominik_combined_screentime
    name: Dominik Combined Screentime
    device_class: duration
    unit_of_measurement: h
    icon: mdi:monitor-eye
    state: >
      {% set tv_time = states('sensor.tv_domiroom_daily_runtime') | float(0) %}
      {% set phone_time = states('sensor.a54_domi_daily_screentime') | float(0) %}
      {% set computer_time = states('sensor.computer_domiroom_daily_runtime') | float(0) %}
      {{ (tv_time + phone_time + computer_time) | round(2) }}
