---
binary_sensor:
  - default_entity_id: binary_sensor.hisense_ac_bedroom_automation_block_status
    unique_id: hisense_ac_bedroom_automation_block_status
    name: Hisense AC Bedroom Automation Block Status
    device_class: lock
    icon: >
      {% set lock_status = states('sensor.hisense_ac_bedroom_lock_status') %}
      {% set lock_owner = state_attr('sensor.hisense_ac_bedroom_lock_status', 'owner') %}
      {% if lock_status == 'locked' and lock_owner == 'homeassistant-automation' %}
        mdi:block-helper
      {% else %}
        mdi:check-circle
      {% endif %}
    state: >
      {% set lock_status = states('sensor.hisense_ac_bedroom_lock_status') %}
      {% set lock_owner = state_attr('sensor.hisense_ac_bedroom_lock_status', 'owner') %}
      {% if lock_status == 'locked' and lock_owner != 'homeassistant-automation' %}
        on
      {% else %}
        off
      {% endif %}
    attributes:
      lock_owner: >
        {{ state_attr('sensor.hisense_ac_bedroom_lock_status', 'owner') }}
      lock_expires_at: >
        {{ state_attr('sensor.hisense_ac_bedroom_lock_status', 'expireAt') }}
