---
alias: Alexroom Nanoleaf Lines
id: alexroom_nanoleaf_lines
description: Turn on the nanoleaf lines when power consumption is above 50W
mode: single
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.aqara_wall_outlet_alexroom_power
    above: 40
  - trigger: numeric_state
    entity_id:
      - sensor.aqara_wall_outlet_alexroom_power
    for:
      seconds: 10
    below: 40
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aqara_wall_outlet_alexroom_power
            above: 40
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.lines_5c30
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aqara_wall_outlet_alexroom_power
            below: 40
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.lines_5c30
