---
alias: Basement Lighting Control
id: basement_lighting
mode: single
triggers:
  - trigger: state
    entity_id:
      - group.motion_basement
    to: "on"
  - platform: time_pattern
    minutes: "/1"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "on"
          - condition: time
            after: "08:00:00"
            before: "00:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "off"
              - condition: state
                entity_id: light.basement
                state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.gledopto_dimmer_stairs_basement
            data:
              brightness: 255
          - action: scene.turn_on
            target:
              entity_id: scene.basement_working
            data:
              transition: 20
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "on"
          - condition: time
            after: "00:00:00"
            before: "08:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "off"
              - condition: state
                entity_id: light.basement
                state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.gledopto_dimmer_stairs_basement
            data:
              brightness: 255
          - action: scene.turn_on
            target:
              entity_id: scene.basement_relax
            data:
              transition: 20
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "off"
            for:
              hours: 0
              minutes: 10
              seconds: 0
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "on"
              - condition: state
                entity_id: light.basement
                state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id:
                - light.basement
                - light.gledopto_dimmer_stairs_basement
