---
alias: Reset Basement Window Open Time Daily
id: basement_window_open_time_reset
description: Resets the window open counter at midnight
mode: single
triggers:
  - platform: time
    at: "00:00:00"
actions:
  - service: input_number.set_value
    target:
      entity_id: input_number.basement_window_open_counter
    data:
      value: 0
