---
alias: Count Basement Window Open Time
id: basement_window_open_time_count
description: Increments the window open counter every second when window is open
triggers:
  - platform: time_pattern
    seconds: "/1"
conditions:
  - condition: state
    entity_id: binary_sensor.aqara_contact_window_basement_contact
    state: "on"
actions:
  - service: input_number.increment
    target:
      entity_id: input_number.basement_window_open_counter
mode: single
