---
alias: basement_light
id: basement_light
description: Turn on the basement light when motion is detected
mode: single
triggers:
  - trigger: state
    entity_id:
      - group.motion_basement
    to: "on"
  - trigger: state
    entity_id:
      - group.motion_basement
    to: "off"
    for:
      minutes: 10
  - trigger: time
    at: "08:00:01"
  - trigger: time
    at: "23:00:01"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "on"
          - condition: time
            after: "08:00:00"
            before: "23:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "off"
              - condition: state
                entity_id: light.basement
                state: "off"
              - condition: numeric_state
                entity_id: light.basement
                attribute: brightness
                below: 235 # scene.basement_working brightness value
                above: 235 # scene.basement_working brightness value
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.gledopto_dimmer_stairs_basement
            data:
              brightness: 255
          - action: scene.turn_on
            target:
              entity_id: scene.basement_working
          - action: system_log.write
            data:
              level: info
              message: scene.basement_working turned on
              logger: homeassistant.components.automation.basement_light
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "on"
          - condition: time
            after: "23:00:00"
            before: "08:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "off"
              - condition: state
                entity_id: light.basement
                state: "off"
              - condition: numeric_state
                entity_id: light.basement
                attribute: brightness
                below: 115 # scene.basement_relax brightness value
                above: 115 # scene.basement_relax brightness value
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.gledopto_dimmer_stairs_basement
            data:
              brightness: 255
          - action: scene.turn_on
            target:
              entity_id: scene.basement_relax
          - action: system_log.write
            data:
              level: info
              message: scene.basement_relax turned on
              logger: homeassistant.components.automation.basement_light
      - conditions:
          - condition: state
            entity_id: group.motion_basement
            state: "off"
            for:
              hours: 0
              minutes: 10
              seconds: 0
          - condition: or
            conditions:
              - condition: state
                entity_id: light.gledopto_dimmer_stairs_basement
                state: "on"
              - condition: state
                entity_id: light.basement
                state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id:
                - light.basement
                - light.gledopto_dimmer_stairs_basement
          - action: system_log.write
            data:
              level: info
              message: light.basement turned off
              logger: homeassistant.components.automation.basement_light
