---
alias: Bathroom Nanoleaf Skylight motion automation
id: bathroom_nanoleaf
mode: single
triggers:
  - platform: time_pattern
    minutes: "/1"
  - trigger: state
    entity_id:
      - binary_sensor.sensor_bathroom_sr501_pir_motion
    to: "on"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "on"
          - condition: time
            after: "08:00:00"
            before: "00:00:00"
          - condition: state
            entity_id: light.skylight_8a41
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
            data:
              brightness: 255
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "on"
          - condition: time
            after: "00:00:00"
            before: "08:00:00"
          - condition: state
            entity_id: light.skylight_8a41
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
            data:
              brightness: 77
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "off"
            for:
              hours: 0
              minutes: 10
              seconds: 0
          - condition: state
            entity_id: light.skylight_8a41
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a41
