---
mode: single
alias: Bathroom Light Switch
id: bathroom_light_switch
description: Handle actions from the Senic Wall Switch in the bathroom
triggers:
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_bathroom_action
    from: null
    to: press_1
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_bathroom_action
    from: null
    to: press_2
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_bathroom_action
    from: null
    to: press_3
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_bathroom_action
    from: null
    to: press_4
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |-
              {{
                (
                  states.sensor.senic_wall_switch_bathroom_action.state == 'press_1'
                  or states.sensor.senic_wall_switch_bathroom_action.state == 'press_2'
                )
                and (
                  states.switch.shelly_1gen4_light_bathroom.state == 'off'
                  or states.light.skylight_8a41.state == 'off'
                )
              }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a41 turned ON by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
          - action: switch.turn_on
            target:
              entity_id: switch.shelly_1gen4_light_bathroom
          - action: system_log.write
            data:
              level: info
              message: switch.shelly_1gen4_light_bathroom turned ON by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
      - conditions:
          - condition: template
            value_template: |-
              {{
                (
                  states.sensor.senic_wall_switch_bathroom_action.state == 'press_1'
                  or states.sensor.senic_wall_switch_bathroom_action.state == 'press_2'
                )
                and (
                  states.switch.shelly_1gen4_light_bathroom.state == 'on'
                  or states.light.skylight_8a41.state == 'on'
                )
              }}
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a41
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a41 turned OFF by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
          - action: switch.turn_off
            target:
              entity_id: switch.shelly_1gen4_light_bathroom
          - action: system_log.write
            data:
              level: info
              message: switch.shelly_1gen4_light_bathroom turned OFF by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
      - conditions:
          - condition: template
            value_template: |-
              {{
                (
                  states.sensor.senic_wall_switch_bathroom_action.state == 'press_3'
                  or states.sensor.senic_wall_switch_bathroom_action.state == 'press_4'
                )
                and states.switch.shelly_1gen4_ventilation_bathroom.state == 'off'
              }}
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.shelly_1gen4_ventilation_bathroom
          - action: system_log.write
            data:
              level: info
              message: Ventilation turned ON by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
      - conditions:
          - condition: template
            value_template: |-
              {{
                (
                  states.sensor.senic_wall_switch_bathroom_action.state == 'press_3'
                  or states.sensor.senic_wall_switch_bathroom_action.state == 'press_4'
                )
                and states.switch.shelly_1gen4_ventilation_bathroom.state == 'on'
              }}
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.shelly_1gen4_ventilation_bathroom
          - action: system_log.write
            data:
              level: info
              message: Ventilation turned OFF by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.bathroom_light_switch
