---
alias: bathroom_nanoleaf
id: bathroom_nanoleaf
description: Bathroom Nanoleaf Skylight motion automation
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.sensor_bathroom_sr501_pir_motion
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.sensor_bathroom_sr501_pir_motion
    to: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "on"
          - condition: time
            after: "08:00:00"
            before: "00:00:00"
          - condition: state
            entity_id: light.skylight_8a41
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
            data:
              brightness: 255
          - action: system_log.write
            data:
              level: info
              message: "light.skylight_8a41 turned on { brightness: 255 }"
              logger: homeassistant.components.automation.bathroom_nanoleaf
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "on"
          - condition: time
            after: "00:00:00"
            before: "08:00:00"
          - condition: state
            entity_id: light.skylight_8a41
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
            data:
              brightness: 77
          - action: system_log.write
            data:
              level: info
              message: "light.skylight_8a41 turned on { brightness: 77 }"
              logger: homeassistant.components.automation.bathroom_nanoleaf
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "off"
            for:
              hours: 0
              minutes: 10
              seconds: 0
          - condition: state
            entity_id: light.skylight_8a41
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a41
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a41 turned off
              logger: homeassistant.components.automation.bathroom_nanoleaf
