alias: Bathroom Nanoleaf Skylight motion automation
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.sensor_bathroom_sr501_pir_motion
    to: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - trigger: state
    entity_id:
      - binary_sensor.sensor_bathroom_sr501_pir_motion
    to: "on"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a41
      - conditions:
          - condition: state
            entity_id: binary_sensor.sensor_bathroom_sr501_pir_motion
            state: "off"
            for:
              hours: 0
              minutes: 10
              seconds: 0
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a41
