---
alias: Bedroom Aqara Switches
id: bedroom_aqara_switches
description: >
  Controls skylight with Aqara switches - single press toggles light,
  double press cycles between brightness levels
mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - sensor.aqara_switch_bedroom_1_action
      - sensor.aqara_switch_bedroom_2_action

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.state in ['single', 'double'] }}

variables:
  action_type: "{{ trigger.to_state.state }}"
  current_brightness: "{{ state_attr('light.skylight_9aa7', 'brightness') | default(120) }}"

action:
  - choose:
      # Single press - Toggle light
      - conditions:
          - condition: template
            value_template: "{{ action_type == 'single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: light.skylight_9aa7

      # Double press - Cycle brightness
      - conditions:
          - condition: template
            value_template: "{{ action_type == 'double' }}"
        sequence:
          - choose:
              # If brightness is ≥ 50, set to 50
              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness >= 50 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.skylight_9aa7
                    data:
                      brightness: 50

              # If brightness is < 50, set to 120
              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness < 50 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: light.skylight_9aa7
                    data:
                      brightness: 120
