---
alias: Climate Livingroom Track Start Time
id: climate_livingroom_track_start_time
description: >
  Updates the climate_livingroom_start_time whenever the Livingroom AC changes from off to any active mode
mode: single
trigger:
  - platform: state
    entity_id: climate.livingroom
    from: "off"
condition:
  # Only run if changing to any active mode (not to "off" or "unknown")
  - condition: template
    value_template: >
      {{
        trigger.to_state.state != 'off' and
        trigger.to_state.state != 'unknown' and
        trigger.to_state.state != 'unavailable'
      }}
action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.climate_livingroom_start_time
    data:
      datetime: "{{ now() }}"
  # Log the action
  - service: system_log.write
    data:
      level: info
      message: "Updated Livingroom AC start time: mode changed from off to {{ trigger.to_state.state }}"
      logger: homeassistant.components.automation.track_ac_livingroom_start_time
