---
alias: Climate Livingroom Auto Off At Night
id: climate_livingroom_auto_off_at_night
description: >
  Automatically turns off the livingroom AC after 23:00
mode: single
trigger:
  - platform: time_pattern
    minutes: "/5"

condition:
  # Only act if the climate is currently on, and there is no manual override
  - condition: template
    value_template: >
      {{
        states('climate.livingroom') == 'cool'
        and states('sensor.hisense_ac_livingroom_automation_block_status') == 'allowed'
        and (now().hour >= 23 or now().hour < 6)
      }}

actions:
  # Release existing lock if it exists
  - action: rest_command.release_lock
    data:
      name: hisense_ac_livingroom
  # Turn off the AC
  - action: climate.turn_off
    target:
      entity_id: climate.livingroom
  # Log the action
  - action: system_log.write
    data:
      level: info
      message: Livingroom AC turned off after 23:00.
      logger: >-
        homeassistant.components.automation.climate_livingroom_auto_off_at_night
