---
alias: Office AC Auto On
id: climatge_office_auto_on
description: >
  Automatically turns on the office AC when the temperature is above 23°C,
  the window is closed, and the weather forecast temperature is above 25°C.
  The automation checks every 5 minutes and respects time constraints.
mode: single
trigger:
  - platform: time_pattern
    minutes: "/5"
condition:
  - condition: template
    value_template: >
      {% set current_time = now() %}
      {{
        current_time.strftime('%H:%M') >= '09:30'
        and         current_time.strftime('%H:%M') < '22:00'
        and states('sensor.qingping_office_temperature') | float > 23
        and states('binary_sensor.aqara_contact_window_office_contact') == 'off'
        and states('sensor.weather_forecast_temperature_forecast') | float > 25
        and states('sensor.hisense_ac_office_lock_status') != 'locked'
        and states('binary_sensor.hisense_ac_office_automation_block_status') == 'off'
      }}
actions:
  - action: script.cool_office
    data:
      reason: hot day and office temperature to high
