---
alias: Domiroom Nanoleaf automation
id: domiroom_nanoleaf
description: Turn on the nanoleaf shape when computer is on
mode: single
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.aqara_wall_outlet_dominikroom_power
    above: 100
  - trigger: numeric_state
    entity_id:
      - sensor.aqara_wall_outlet_dominikroom_power
    for:
      seconds: 10
    below: 100
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aqara_wall_outlet_dominikroom_power
            above: 100
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.shapes_a6dc
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aqara_wall_outlet_dominikroom_power
            below: 100
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.shapes_a6dc
