---
alias: Domiroom Ceiling Light motion automation
id: domiroom_ceiling_light
description: Turn on the ceiling light when motion is detected in the room
mode: single
trigger:
  - platform: state
    entity_id: group.motion_domiroom
    to: "on"
condition:
  - condition: time
    after: "09:00:00"
    before: "22:00:00"
  - condition: numeric_state
    entity_id: sensor.aqara_wall_outlet_dominikroom_power
    below: 50 # TV is off if power is bellow
actions:
  - action: light.turn_on
    target:
      entity_id: light.led_ceiling_light_domiroom
