---
alias: frontdoor_camera_motion_snapshots
id: frontdoor_camera_motion_snapshots
description: Take snapshots when front door motion is detected
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.front_door_motion
    to: "on"
actions:
  # First request a stream update
  - service: homeassistant.update_entity
    target:
      entity_id: camera.front_door_snapshot
  # Wait for the stream to update
  - delay: 3
  # Take multiple snapshots with slight delays to catch the action
  - repeat:
      count: 3
      sequence:
        - action: camera.snapshot
          data:
            filename: /data/ring-snapshots/{{ now().strftime("%Y-%m-%d_%H-%M-%S") }}_{{repeat.index}}.jpg
          target:
            entity_id: camera.front_door_snapshot
        - delay: 2
