---
alias: frontdoor_camera_motion_snapshots
id: frontdoor_camera_motion_snapshots
description: Take snapshots when front door motion is detected
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.front_door_motion
    to: "on"
actions:
  # Take multiple snapshots with slight delays to catch the action
  - while:
      condition: state
      entity_id: binary_sensor.front_door_motion
      state: "on"
      sequence:
        - action: press.button
          data:
            entity_id: button.front_door_take_snapshot
        - action: homeassistant.update_entity
          data:
            entity_id:
              - camera.front_door_snapshot
        - action: camera.snapshot
          data:
            filename: /data/ring-snapshots/{{ now().strftime("%Y-%m-%d_%H-%M-%S") }}.jpg
          target:
            entity_id: camera.front_door_snapshot
        - delay: 1 # Wait 1 seconds between snapshots
