---
alias: Garden Tomato Irrigation
id: garden_tomato_irrigation
description: Water tomatoes after sunrise and during hot days, with lock tracking
mode: single
triggers:
  # Morning watering after sunrise
  - platform: sun
    event: sunrise
    offset: "+00:30:00" # 30 minutes after sunrise
    id: morning_watering

  # Check every hour during the day for additional watering
  # - platform: time_pattern
  #   hours: "/1"
  #   id: hourly_check

conditions: []

actions:
  - choose:
      # Morning watering (always runs if no precipitation)
      - conditions:
          - condition: trigger
            id: morning_watering
          - condition: template
            value_template: "{{ not (states('sensor.openmeteo_precipitation') | float(0) > 0) }}"
          - condition: template
            value_template: "{{ states('sensor.woox_irrigation_garden2_automation_block_status') == 'off' }}"
        sequence:
          - service: script.start_tomato_watering
            data:
              reason: Morning watering after sunrise
