---
alias: kitchen_nanoleaf
id: kitchen_nanoleaf
description: Kitchen Nanoleaf Skylight motion automation
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.mijia_motion_kitchen_occupancy
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.mijia_motion_kitchen_occupancy
    to: "off"
    for:
      minutes: 5
  - trigger: state
    entity_id:
      - group.motion_downstairs
    to: "off"
    for:
      minutes: 20
conditions: []
actions:
  - choose:
      - conditions:
          # turn light on if motion in the kitchen between 8:00 and 00:00
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "on"
          - condition: time
            after: "07:00:00"
            before: "00:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.skylight_8a30
                state: "off"
              - condition: numeric_state
                entity_id: light.skylight_8a30
                attribute: brightness
                below: 255
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 255
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned on (brightness=255)
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          # turn on light dimmed if motion is detected in the kitchen between 00:00 and 07:00
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "on"
          - condition: time
            after: "00:00:00"
            before: "07:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.skylight_8a30
                state: "off"
              - condition: numeric_state
                entity_id: light.skylight_8a30
                attribute: brightness
                above: 51
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 51
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned on (brightness=51)
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          # dimm light if no motion for 5 minutes in the kitchen
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "off"
            for:
              hours: 0
              minutes: 5
              seconds: 0
          - condition: state
            entity_id: light.skylight_8a30
            state: "on"
          - condition: numeric_state
            entity_id: light.skylight_8a30
            attribute: brightness
            above: 51
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 51
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned on (brightness=51)
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          # turn light off if group.motion_downstairs is off for 15 minutes
          - condition: state
            entity_id: group.motion_downstairs
            state: "off"
            for:
              minutes: 15
          - condition: state
            entity_id: light.skylight_8a30
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a30
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned off
              logger: homeassistant.components.automation.kitchen_nanoleaf
