---
alias: Kitchen Nanoleaf Skylight motion automation
id: kitchen_nanoleaf
mode: single
triggers:
  - platform: time_pattern
    minutes: "/1"
  - trigger: state
    entity_id:
      - binary_sensor.mijia_motion_kitchen_occupancy
    to: "on"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "on"
          - condition: time
            after: "07:00:00"
            before: "00:00:00"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.skylight_8a30
                state: "off"
              - condition: numeric_state
                entity_id: light.skylight_8a30
                attribute: brightness
                below: 255
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 255
      - conditions:
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "on"
          - condition: time
            after: "00:00:00"
            before: "07:00:00"
          - condition: state
            entity_id: light.skylight_8a30
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 51
      - conditions:
          - condition: state
            entity_id: binary_sensor.mijia_motion_kitchen_occupancy
            state: "off"
            for:
              hours: 0
              minutes: 5
              seconds: 0
          - condition: state
            entity_id: light.skylight_8a30
            state: "on"
          - condition: numeric_state
            entity_id: light.skylight_8a30
            attribute: brightness
            above: 51
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 51
