---
alias: kitchen_nanoleaf
id: kitchen_nanoleaf
description: Kitchen Nanoleaf Skylight motion automation
mode: single
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.mijia_motion_kitchen_occupancy
      - binary_sensor.mijia_motion_table_occupancy
    to: "on"
    id: motion_on
  - trigger: state
    entity_id:
      - binary_sensor.mijia_motion_kitchen_occupancy
    to: "off"
    for:
      minutes: 5
    id: kitchen_idle
  - trigger: state
    entity_id:
      - group.motion_downstairs
    to: "off"
    for:
      minutes: 15
    id: all_motion_off
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: template
            value_template: >
              {{
                states('light.skylight_8a30') == 'off'
                or state_attr('light.skylight_8a30', 'brightness') | int(0) < (51 if now().hour >= 0 and now().hour < 7 else 255)
              }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: >
                {{ 51 if now().hour >= 0 and now().hour < 7 else 255 }}
          - action: system_log.write
            data:
              level: info
              message: "light.skylight_8a30 turned on (brightness={{ 51 if now().hour >= 0 and now().hour < 7 else 255 }})"
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          - condition: trigger
            id: kitchen_idle
          - condition: template
            value_template: >
              {{
                states('input_boolean.movie_mode') == 'on'
                and states('light.skylight_8a30') == 'on'
              }}
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a30
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned off - movie mode auto-off
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          - condition: trigger
            id: kitchen_idle
          - condition: template
            value_template: >
              {{
                states('input_boolean.movie_mode') == 'off'
                and states('light.skylight_8a30') == 'on'
                and states('binary_sensor.mijia_motion_table_occupancy') == 'off'
                and state_attr('light.skylight_8a30', 'brightness') | int(0) > 51
              }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.skylight_8a30
            data:
              brightness: 51
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 dimmed to 51 - kitchen idle
              logger: homeassistant.components.automation.kitchen_nanoleaf
      - conditions:
          - condition: trigger
            id: all_motion_off
          - condition: template
            value_template: >
              {{
                states('light.skylight_8a30') == 'on'
              }}
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.skylight_8a30
          - action: system_log.write
            data:
              level: info
              message: light.skylight_8a30 turned off - no motion downstairs
              logger: homeassistant.components.automation.kitchen_nanoleaf
