---
mode: single
alias: Laundryroom Light Switch
id: laundryroom_light_switch
description: Handle actions from the Senic Wall Switch in the laundryroom
triggers:
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_laundryroom_action
    from: null
    to: press_1
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_laundryroom_action
    from: null
    to: press_2
  - trigger: state
    entity_id:
      - sensor.senic_wall_switch_laundryroom_action
    from: null
    to: press_3
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |-
              {{
                states('sensor.senic_wall_switch_laundryroom_action') == 'press_1'
                and states('switch.shelly_1gen4_light_laundryroom') == off
              }}
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.shelly_1gen4_light_laundryroom
          - action: system_log.write
            data:
              level: info
              message: Light turned ON by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.laundryroom_light_switch
      - conditions:
          - condition: template
            value_template: |-
              {{
                states('sensor.senic_wall_switch_laundryroom_action') == 'press_2'
                and states('switch.shelly_1gen4_light_laundryroom') == on
              }}
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.shelly_1gen4_light_laundryroom
          - action: system_log.write
            data:
              level: info
              message: Light turned OFF by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.laundryroom_light_switch
      - conditions:
          - condition: template
            value_template: |-
              {{
                states('sensor.senic_wall_switch_laundryroom_action') == 'press_3'
                and states('switch.shelly_1gen4_ventilation_laundryroom') == off
              }}
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.shelly_1gen4_ventilation_laundryroom
          - action: system_log.write
            data:
              level: info
              message: Ventilation turned ON by Senic Wall Switch
              logger: >-
                homeassistant.components.automation.laundryroom_light_switch
