---
alias: Nvidia Shield Movie Mode
id: nvidia_shield_movie_mode
description: >
  Automatically enable movie mode when Nvidia Shield is playing,
  which prevents downstairs light automations from triggering.
mode: single
triggers:
  - trigger: state
    entity_id:
      - media_player.nvidia_shield
    to: playing
    id: shield_on
  - trigger: state
    entity_id:
      - media_player.nvidia_shield
    to: paused
    id: shield_on
  - trigger: state
    entity_id:
      - media_player.nvidia_shield
    to: idle
    id: shield_on
  - trigger: state
    entity_id:
      - media_player.nvidia_shield
    to: "off"
    id: shield_off
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: shield_on
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.movie_mode
          - action: system_log.write
            data:
              level: info
              message: Movie mode enabled - Shield is on
              logger: homeassistant.components.automation.nvidia_shield_movie_mode
      - conditions:
          - condition: trigger
            id: shield_off
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.movie_mode
          - action: system_log.write
            data:
              level: info
              message: Movie mode disabled - Shield is off
              logger: homeassistant.components.automation.nvidia_shield_movie_mode
