---
# create a new automation for homeassistant:
# light.office should turn on if one of the motion sensors
# group.motion_office is on and the light is off
# light.office should switch to the scene reading between 06:00 and 08:00
# light.office should switch to the scene working between 08:00 and 12:00
# light.office should switch to the scene concentration between 12:00 and 14:00
# light.office should switch to the scene working between 14:00 and 21:00
# light.office should switch to the scene evening between 21:00 and 23:00
# light.office should switch to the scene night between 23:00 and 06:00
# when the light is on and there is no motion on the group.motion_office for 15 minutes between 08:00 and 00:00, the light should switch to scene relax
# when the light is on and there is no motion on the group.motion_office for 20 minutes between 08:00 and 00:00, the light should switch off
# when the light is on and there is no motion on the group.motion_office for 10 minutes between 00:00 and 08:00, the light should switch off

alias: office_light
id: office_light
description: Turn on the office light when motion is detected
mode: single
triggers:
  - trigger: state
    entity_id:
      - group.motion_office
    to: "on"
  - trigger: state
    entity_id:
      - group.motion_office
    to: "off"
    for:
      minutes: 10
  - trigger: state
    entity_id:
      - group.motion_office
    to: "off"
    for:
      minutes: 15
  - trigger: state
    entity_id:
      - group.motion_office
    to: "off"
    for:
      minutes: 20
  - trigger: time
    at: "06:00:01"
  - trigger: time
    at: "08:00:01"
  - trigger: time
    at: "12:00:01"
  - trigger: time
    at: "14:00:01"
  - trigger: time
    at: "21:00:01"
  - trigger: time
    at: "23:00:01"
  - trigger: time
    at: "00:00:01"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: time
            after: "23:00:00"
            before: "06:00:00"
          - condition: template
            value_template: >-
              {{
                states('sensor.office_light_automation_block_status') == 'allowed'
                and states('group.motion_office') == 'on'
                and (
                  states('light.office') == 'off'
                  or state_attr('light.office', 'brightness') != 45
                )
              }}
            # scene.office_night brightness value = 45
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_night
          - action: system_log.write
            data:
              level: info
              message: scene.office_night turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "08:00:00"
          - condition: template
            value_template: >-
              {{
                states('sensor.office_light_automation_block_status') == 'allowed'
                and states('group.motion_office') == 'on'
                and (
                  states('light.office') == 'off'
                  or state_attr('light.office', 'brightness') != 220
                )
              }}
            # scene.office_reading brightness value = 220
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_reading
          - action: system_log.write
            data:
              level: info
              message: scene.office_reading turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "08:00:00"
                before: "12:00:00"
              - condition: time
                after: "14:00:00"
                before: "21:00:00"
          - condition: template
            value_template: >-
              {{
                states('sensor.office_light_automation_block_status') == 'allowed'
                and states('group.motion_office') == 'on'
                and (
                  states('light.office') == 'off'
                  or state_attr('light.office', 'brightness') != 235
                )
              }}
            # scene.office_working brightness value = 235
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_working
          - action: system_log.write
            data:
              level: info
              message: scene.office_working turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: time
            after: "12:00:00"
            before: "14:00:00"
          - condition: template
            value_template: >-
              {{
                states('sensor.office_light_automation_block_status') == 'allowed'
                and states('group.motion_office') == 'on'
                and (
                  states('light.office') == 'off'
                  or state_attr('light.office', 'brightness') != 255
                )
              }}
            # scene.office_concentration brightness value = 255
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_concentration
          - action: system_log.write
            data:
              level: info
              message: scene.office_concentration turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: time
            after: "21:00:00"
            before: "23:00:00"
          - condition: template
            value_template: >-
              {{
                states('sensor.office_light_automation_block_status') == 'allowed'
                and states('group.motion_office') == 'on'
                and (
                  states('light.office') == 'off'
                  or state_attr('light.office', 'brightness') != 170
                )
              }}
            # scene.office_evening brightness value = 170
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_evening
          - action: system_log.write
            data:
              level: info
              message: scene.office_evening turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: state
            entity_id: group.motion_office
            state: "off"
            for:
              minutes: 10
          - condition: time
            after: "00:00:00"
            before: "08:00:00"
          - condition: state
            entity_id: light.office
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.office
          - action: system_log.write
            data:
              level: info
              message: light.office turned off
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: state
            entity_id: group.motion_office
            state: "off"
            for:
              minutes: 15
          - condition: time
            after: "08:00:00"
            before: "00:00:00"
          - condition: state
            entity_id: light.office
            state: "on"
        sequence:
          - action: scene.turn_on
            data: {}
            target:
              entity_id: scene.office_relax
          - action: system_log.write
            data:
              level: info
              message: scene.office_relax turned on
              logger: homeassistant.components.automation.office_light
      - conditions:
          - condition: state
            entity_id: group.motion_office
            state: "off"
            for:
              minutes: 20
          - condition: time
            after: "08:00:00"
            before: "00:00:00"
          - condition: state
            entity_id: light.office
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.office
          - action: system_log.write
            data:
              level: info
              message: light.office turned off
              logger: homeassistant.components.automation.office_light
