---
alias: Reset Daily Herb Watering Counter
id: reset_daily_herb_watering_counter
description: Reset the daily herb watering counter at midnight
mode: single
triggers:
  - platform: time
    at: "00:00:00"
actions:
  - service: counter.reset
    target:
      entity_id: counter.daily_herb_watering_count
  - service: system_log.write
    data:
      level: info
      message: Reset daily herb watering counter
      logger: homeassistant.components.automation.reset_daily_herb_watering_counter
