---
alias: Reset Daily Tomato Watering Counter
id: reset_daily_tomato_watering_counter
description: Reset the daily tomato watering counter at midnight
mode: single
triggers:
  - platform: time
    at: "00:00:00"
actions:
  - service: counter.reset
    target:
      entity_id: counter.daily_tomato_watering_count
  - service: system_log.write
    data:
      level: info
      message: Reset daily tomato watering counter
      logger: homeassistant.components.automation.reset_daily_tomato_watering_counter
