---
alias: Test Logging
id: test_logging
description: Test the logging
mode: single
triggers:
  - platform: time_pattern
    minutes: "/1"
actions:
  - service: system_log.write
    data:
      level: info
      message: Hello World!
      logger: homeassistant.components.automation.test_logging
