---
alias: Ventilation Bathroom Auto On
id: ventilation_bathroom_auto_on
description: >
  Automatically turns on bathroom ventilation when humidity exceeds 58%.
mode: single
triggers:
  - trigger: time_pattern
    minutes: "/5"

conditions:
  # Only turn on if the ventilation is currently off and humidity is above threshold
  - condition: template
    value_template: >
      {{
        states('switch.shelly_1gen4_ventilation_bathroom') != 'on'
        and states('sensor.sensor_bathroom_sensor_bathroom_htu21d_humidity') | float(0) > 58
      }}
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.shelly_1gen4_ventilation_bathroom
  - action: system_log.write
    data:
      level: info
      message: Ventilation turned ON - humidity over threshold
      logger: homeassistant.components.automation.ventilation_bathroom_auto_on
