---
name: Check Home Assistant Configuration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  home-assistant:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4.1
        with:
          path: ./
          secrets: ci-secrets.yaml
          version: stable
