---
name: Check Home Assistant Configuration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**
      - .taskfiles/**
      - docu/**

jobs:
  home-assistant:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Update external directory path for CI
        run: |
          sed -i 's|- /data|- ./data|g' configuration.yaml

      - name: Create data directory
        run: mkdir -p ./data

      - name: Create files
        run: touch automations.yaml

      # https://github.com/marketplace/actions/frenck-s-home-assistant-core-configuration-check
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4.1
        with:
          path: ./
          secrets: ci-secrets.yaml
          version: stable
